//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactiveUIAroundMe.Portable.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Config() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ReactiveUIAroundMe.Portable.Resources.Config", typeof(Config).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ClockSignalRUri {
            get {
                return ResourceManager.GetString("ClockSignalRUri", resourceCulture);
            }
        }
        
        public static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        public static string TestUrl {
            get {
                return ResourceManager.GetString("TestUrl", resourceCulture);
            }
        }
        
        public static string GoogleMapsApiUrl {
            get {
                return ResourceManager.GetString("GoogleMapsApiUrl", resourceCulture);
            }
        }
        
        public static string DirectionsUrl {
            get {
                return ResourceManager.GetString("DirectionsUrl", resourceCulture);
            }
        }
        
        public static string DirectionParamsUrl {
            get {
                return ResourceManager.GetString("DirectionParamsUrl", resourceCulture);
            }
        }
        
        public static string GoogleApiKey {
            get {
                return ResourceManager.GetString("GoogleApiKey", resourceCulture);
            }
        }
        
        public static string ConsumerKeyProduction {
            get {
                return ResourceManager.GetString("ConsumerKeyProduction", resourceCulture);
            }
        }
        
        public static string ConsumerSecretProduction {
            get {
                return ResourceManager.GetString("ConsumerSecretProduction", resourceCulture);
            }
        }
        
        public static string AuthDeviceUrl {
            get {
                return ResourceManager.GetString("AuthDeviceUrl", resourceCulture);
            }
        }
        
        public static string GetEReactiveUIAroundMesByLocationUrl {
            get {
                return ResourceManager.GetString("GetEReactiveUIAroundMesByLocationUrl", resourceCulture);
            }
        }
        
        public static string GetEReactiveUIAroundMeByIdUrl {
            get {
                return ResourceManager.GetString("GetEReactiveUIAroundMeByIdUrl", resourceCulture);
            }
        }
        
        public static string TokenEndPointUrl {
            get {
                return ResourceManager.GetString("TokenEndPointUrl", resourceCulture);
            }
        }
    }
}
